### ISSUE TITLE
iOS 8: ages disappeared 

### ISSUE THREAD

**Issue by ShelbyRN** [p2/growth-charts#10]
This is a fantastic app. I'm a nurse home visitor and use it for work all the time. I also recommend it to my co-workers frequently.
One of the great features is having each child's exact age immediately upon opening the app. However, when I updated to iOS8 yesterday, that feature disappeared. Now, it simply shows the birthday. Hoping this will be fixed in the coming update!
I'd be thrilled if the app were also available for Microsoft surface tablets. Thank you!

**Comment by p2** [comment]
Thanks a lot Shelby! Yes, that issue is also fixed in the upcoming update. And please be careful as some other things might not work reliably with iOS 8. The update has been at Apple for almost 2 weeks now, I hope they release it soon!

No plans for Windows support I'm afraid.

**Comment by p2** [comment]
Good news, version 2.0 has just been approved and should be available in the App Store in the next hours.

**Comment by ShelbyRN** [comment]
Thank you for your quick response and your great app!
I'm eagerly awaiting the update and also hope it's released soon.
Best,
Shelby

**Comment by ShelbyRN** [comment]
Thanks for the update and your hard work. I'll be among the first to download. :)
Best, Shelby
