### ISSUE TITLE
Not working since update. 

### ISSUE THREAD

**Issue by andreajvaughan** [p2/growth-charts#12]
Updated the app. Now I only get a black screen! Please fix :). Do not have the newest OS as it won't download on the slow internet, but that shouldn't stop ppl from using updated apps

**Comment by p2** [comment]
Sorry to hear! You need iOS 7 or iOS 8, do you have either of these? It seems to work fine for me, which device do you have?

**Comment by andreajvaughan** [comment]
I have iOS 7.

**Comment by p2** [comment]
It's working on my iPhone 4S with iOS 7, which device are you on?

**Comment by andreajvaughan** [comment]
Generation 5 iPod with iOS 7. It worked up until 2 weeks ago. Then after I updated it the app it stopped. Just a black screen.

**Comment by p2** [comment]
Thanks for reporting, I'll look into it. Sorry for the trouble!

**Comment by p2** [comment]
Andrea, can you test the latest update (v 2.0.1) and see if you're still having the issue?

**Comment by andreajvaughan** [comment]
Yes!!! Thank you so much!

**Comment by p2** [comment]
Very good, thanks a lot for reporting!

Pascal
