### ISSUE TITLE
Option for saving data to other devices

### ISSUE THREAD

**Issue by kiddydoc67** [p2/growth-charts#15]
This is a very good free app. I wish they can add functions like saving data, and other advanced features. I am willing to spend for a paid app PRO version of this to better use at clinic. Thank you.

**Comment by p2** [comment]
Yes, sharing data between devices would be great. I have this on my list but not decided on how and when to implement it.

**Comment by p2** [comment]
This is now implemented in **version 2.1**, which should appear in the App Store soon. You can export all children, or one at a time, by pressing the new ⬆️ button that appears below the children list and when viewing one kid.
