### ISSUE TITLE
Why are there circles around the data points?

### ISSUE THREAD

**Issue by jennclarke** [p2/growth-charts#2]
Can this be removed? Thank you.  I think it makes the chart "busy" looking.

**Comment by p2** [comment]
You can choose how the data points look by tapping one of them, then tapping the blue arrow in the bottom right. See the screenshots, hope this helps!

![step 1](https://f.cloud.github.com/assets/358485/1708850/1bfcdaca-6115-11e3-9161-63b64c667b0f.png)
![step 2](https://f.cloud.github.com/assets/358485/1708851/1f51e9ea-6115-11e3-88c1-41338c65ef64.png)
