### ISSUE TITLE
Backing up data

### ISSUE THREAD

**Issue by leahga** [p2/growth-charts#21]
How can I back up my data? I use your app to track the growth of my toddler twins, but lost 3 years of data points in the upgrade to iOS 8- I don't want to re enter them all until I'm sure how to back it up. Thank you.

**Comment by p2** [comment]
Sorry to hear, this shouldn't happen! Did you restore when you updated to iOS 8?

In any case, there is yet no real backup mechanism. You can however with iTunes make a copy of your database. Connect your iPhone/iPad/iPod, open iTunes, click your device and on the left side choose _"Apps"_. Scroll to the bottom to the _File Sharing_ section and find _"Charts"_ in the list. When you click it you will see a folder named `db` – copy this folder to your hard drive, it contains all measurements as well as photos.

Should you need to restore you can put this same `db` folder on your device again, via iTunes just like you downloaded it before. I will have to add a true backup/data-sharing option in a future update.

**Comment by p2** [comment]
This is now implemented in **version 2.1**, which should appear in the App Store soon. You can export all children, or one at a time, by pressing the new ⬆️ button that appears below the children list and when viewing one kid.
