### ISSUE TITLE
How to import data to another iOS device?

### ISSUE THREAD

**Issue by Chicapee** [p2/growth-charts#26]
I have both my children's data entered on my iPad but would like it on my new iPhone so I can always have it with me. I figured out how to export a Kids-1.bchkids file to my Dropbox, but can't figure out how to get the info in that file into the Charts app on my iPhone. Can you help me, please?

**Comment by p2** [comment]
It's a little more complicated than one would hope. Here's the 4 steps:

## 1. Open the file within the Dropbox app, you should see a lot of text. Tap the three dots top right.
![import_1](https://user-images.githubusercontent.com/358485/26863142-92f46dea-4b05-11e7-9d38-58b435ffe813.png)

## 2. Tap Export.
![import_2](https://user-images.githubusercontent.com/358485/26863146-9c01a65a-4b05-11e7-8700-6883db232950.png)

## 3. Scroll until you see "Open in..." and tap it:
![import_3](https://user-images.githubusercontent.com/358485/26863150-a079e0ee-4b05-11e7-8473-c0af72e46ba5.png)

## 4. Scroll until you see "Copy to Charts":
![import_4](https://user-images.githubusercontent.com/358485/26863155-a6fe21fa-4b05-11e7-9f06-2408e80f716a.png)
