### ISSUE TITLE
Alphabetical name list

### ISSUE THREAD

**Issue by ksinclair** [p2/growth-charts#3]
Would be Great if patient names would be listed alphabetically!! Is that possible?

Thanks! 

Kellysinclair.rd@gmail.com

**Comment by p2** [comment]
Yes, this is definitely planned, however work on the app has yet to resume.

**Comment by fakhat1** [comment]
How we can list the patients name alphabetically?

**Comment by p2** [comment]
I'm afraid this is not possible in the current version.

**Comment by p2** [comment]
This will finally be fixed in the upcoming version!
