### ISSUE TITLE
How to delete charts?

### ISSUE THREAD

**Issue by dsherw** [p2/growth-charts#33]
Is there a way to delete a child’s file? If so, I can’t seem to figure it out.

I use this app for work and have continually have kids being added to and discharged from my caseload. If there is not a way to delete files then that is going to become a problem really fast because I will amass hundreds of files and have to sift through all of them to find the one I’m looking for... I’ll probably stop using this app if you can’t delete the files.

**Comment by p2** [comment]
Yes. In the child selector view, you can swipe any row left to reveal a "Delete" button.
