### ISSUE TITLE
Data transfer between défices

### ISSUE THREAD

**Issue by mvackel** [p2/growth-charts#4]
Thanks for the great app.
I'd like to suggest a new functionality to transfer data between devices.
This is to transfer data from a child or all children, for instance, from the iPad to the iPhone, or from your device to your doctor's device. Or to backup.
Would be nice to be able to do this, maybe by sending by email the selected data and, at the destination device, opening the file in the app.

**Comment by p2** [comment]
Yes, this is a great suggestion and I have been looking for good ways to implement this into 1.0 without having to resort to email. This is something I want to address once I get some work done for 2.0.

**Comment by mvackel** [comment]
hello, even if you decide to other way of implementation, please keep the email option, as this would be an eclectic way to transfer data - even to other programs or apps. You know how the Apple's world is closed. Thanks again!

On Tuesday, February 25, 2014 2:24 PM, Pascal Pfiffner notifications@github.com wrote:

Yes, this is a great suggestion and I have been looking for good ways to implement this into 1.0 without having to resort to email. This is something I want to address once I get some work done for 2.0.

**Comment by p2** [comment]
Don't worry, I'm not considering Apple-only solutions. ;)

**Comment by p2** [comment]
This is now implemented in **version 2.1**, which should appear in the App Store soon. You can export all children, or one at a time, by pressing the new ⬆️ button that appears below the children list and when viewing one kid.
