### ISSUE TITLE
Request an suggestion

### ISSUE THREAD

**Issue by PEDIATRUCHO** [p2/growth-charts#5]
Hello!!! I have recently discovered your App and it's amazing for me. I'm a pediatrician, and your App makes my work much easier. I would like to make a request and a suggestion:
- Request: please, keep using WHO charts in your app. I am Spanish and I use those charts, as CDC charts are not useful for me. iCloud syncing would be great too, or a way to export and import data.
- Suggesiton: I keep on searching for an app like this for OS X. If you could adapt your iOS app for Mac, I am sure it would be a great success. There isn't any app like this on the Mac App Store. I would pay for it. Please!!!! XD

Thanks for your work

**Comment by p2** [comment]
Thanks, glad you like the app!

Data import/export is definitely a topic, I hope to allocate some time to finally update the app and this will be one of the most important improvements. Interesting idea bringing this to OS X; again time is limited but I find this a nice idea. :)

**Comment by p2** [comment]
Let's keep this open until your suggestions have been implemented.

**Comment by p2** [comment]
A way to export your data is now implemented in **version 2.1**, which should appear in the App Store soon. You can export all children, or one at a time, by pressing the new ⬆️ button that appears below the children list and when viewing one kid.

The Mac version is still not on my plate I'm afraid.

**Comment by rajivramarajan** [comment]
Appreciate all the effort.
Can we expect Import functionality anytime soon? I have been using the App for 2 years, but I just changed my iPad, and the only way I see to transfer the data is to manually enter it again. Correct?

**Comment by p2** [comment]
Version 2.1 has export and import functionality. Export your children to e.g. Dropbox. Then, on another device, open the file in Dropbox and choose "Open in...", then choose _Growth Charts_.

**Comment by rajivramarajan** [comment]
Thank you so much! I followed your steps and I am back on track.
This is a neat app, and some great work!

**Comment by p2** [comment]
Great, good to hear!
