### ISSUE TITLE
Addition of Wt/Lth to 'Show' Page

### ISSUE THREAD

**Issue by LisaSven** [p2/growth-charts#7]
Thanks for a very handy app. I recommend it to colleagues and use it regularly with parents. Along with the length, weight and head circumference details on the WHO 0-24 months show page could you add weight for length values as well? Many thanks!

**Comment by p2** [comment]
Yes, those charts have been prepared some time ago, I hope to finally getting back at the app and publishing an update.

**Comment by p2** [comment]
These will be included in the upcoming new version.
