### ISSUE TITLE
Problems with iOS 8

### ISSUE THREAD

**Issue by nolarad** [p2/growth-charts#9]
New iPhone 6 essentially made the app unusable. Percentiles are not being calculated correctly and app crashes regularly. Please help. Your app has been tremendously helpful.

**Comment by p2** [comment]
I would love to finally publish an update, but there currently is no funding for work on this app so progress is glacial at best I'm afraid.

**Comment by nolarad** [comment]
That is quite unfortunate. Any possibility of ad or industry support? Or perhaps a paid version? I'm a physician and have used your app with my kids and have recommended it frequently.

**Comment by p2** [comment]
Let me see what I can do, there has been a fair amount of work intermittently and I might be able to push a "good enough" version in the next weeks.

**Comment by nolarad** [comment]
Thank you! Can I donate a few dollars via PayPal?

**Comment by p2** [comment]
That's kind, thanks, but no worries, money is not the issue, time is. :)

**Comment by p2** [comment]
Good news, an intensive weekend was productive and the new version will be submitted to Apple in the next week!

**Comment by nolarad** [comment]
Thank you so much!

**Comment by p2** [comment]
Still waiting for Apple to approve, 10 days and counting.

**Comment by p2** [comment]
Good new, version 2.0 has just been approved and should be available in the App Store in the next hours.

**Comment by nolarad** [comment]
Thanks very much! You are a lifesaver
